name: Check and Release

on:
  pull_request:
  push:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check.yml
    with:
      is_pull_request: ${{ github.event_name == 'pull_request' }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}

  release:
    needs: check
    if: >-
      github.event_name == 'push' &&
      contains(fromJSON('["refs/heads/main", "refs/heads/master", "refs/heads/beta", "refs/heads/next", refs/heads/insiders]'), github.ref)
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    secrets: inherit
